name: Lint

on:
  push:
    branches-ignore: [ main ]
    paths:
      - '**/*.tf'
      - '**/*.tfvars'
      - '.tflint.hcl'
      - 'modules/**'
      - 'envs/**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: opentofu/setup-opentofu@v1
        with: { tofu_version: v1.7.3 }

      - name: Check formatting
        run: tofu fmt -check -recursive .

      - name: Cache TFLint plugins
        uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ runner.os }}-${{ hashFiles('.tflint.hcl') }}

      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --init
      - name: Run TFLint (fast)
        run: tflint --recursive