name: Terratest (IAM Developer Role)

on:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1

jobs:
  terratest-iam:
    # Prevent running on forked PRs (no repo secrets there)
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CI_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: gha-iam-terratest
          role-duration-seconds: 3600

      # Sanity check: fail fast if creds are not present
      - name: Who am I? (STS)
        run: aws sts get-caller-identity

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: v1.7.3

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true

      - name: Cache Go build
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Resolve AWS Account ID (for test env)
        id: sts_id
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "AWS_ACCOUNT_ID=$ACCOUNT_ID" >> "$GITHUB_ENV"
          echo "account=$ACCOUNT_ID" >> "$GITHUB_OUTPUT"

      # Run only if there are Go test files under tests/
      - name: Run Terratest (IAM Developer Role)
        if: ${{ hashFiles('tests/**/*.go') != '' }}
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ steps.sts_id.outputs.account }}
        run: |
          set -euo pipefail
          REPORT=tests/test-report.xml
          OUTPUT=tests/output.txt

          if [ -f tests/go.mod ]; then
            echo "Using module in tests/"
            pushd tests >/dev/null
            go mod download
            PKG="./..."
            gotestsum --junitfile "$(basename "$REPORT")" -- \
              go test -run TestIamDeveloperRole -v -timeout 30m "$PKG" | tee "$(basename "$OUTPUT")"
            popd >/dev/null
          elif [ -f go.mod ]; then
            echo "Using root module, targeting ./tests/..."
            go mod download
            PKG="./tests/..."
            mkdir -p tests
            gotestsum --junitfile "$REPORT" -- \
              go test -run TestIamDeveloperRole -v -timeout 30m "$PKG" | tee "$OUTPUT"
          else
            echo "No go.mod found in tests/ or repo root — skipping Terratest."
            exit 0
          fi

      - name: Upload test report (JUnit)
        if: ${{ hashFiles('tests/test-report.xml') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: junit-terratest
          path: tests/test-report.xml
          if-no-files-found: warn

      - name: Upload raw test output
        if: ${{ hashFiles('tests/output.txt') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: terratest-output
          path: tests/output.txt
          if-no-files-found: warn
